### ISSUE TITLE
RockyLinux.exe -- No networking tools found

### ISSUE THREAD

**Issue by hyukishi** [ingchivas/RockyLinuxWSL2#1]
Networking appears to be disabled by default and the usual tools (ip, ifupdown, nmcli) are not found.

**Comment by ingchivas** [comment]
This installation is as barebones as it gets, to install the tools you refer to, you need to get them using yum. Either way, the setupv2.sh script should get you up and running with net-tools, ncurses, and some other useful packages.
Networking is not disabled as default though, just made a clean installation and no networking issues were found.
Try running setupv2.sh and if you get any issue, I could look further into it.

Also, remember to use WSL 2 as WSL 1 is not supported.

![image](https://user-images.githubusercontent.com/51966857/156017868-8ccd06e0-bfd6-4a8a-8872-99fab2efc744.png)

**Comment by hyukishi** [comment]
I've confirmed it is running as WSL 2 along with my other WSL distros. When attempting to yum update -y I just see the following. It doesn't ever complete updating the lists from the repositories.
![image](https://user-images.githubusercontent.com/11379349/156019043-15432049-5842-4cb7-8e83-245c6df698bb.png)

**Comment by ingchivas** [comment]
Well, that's weird, just tried in 3 different machines and it ran with no problems whatsoever. All vanilla unmodified WSL2 installations. Maybe a proxy is blocking it? Maybe with a VPN, it shouldn't have a problem tho. 
Try running ```yum clean all``` and then ```yum -y update```

I'll look further into probable issues, however, I'm not able to reproduce them myself. 

Here I'm trying to reproduce the issue on a vanilla WSL2 install.
![image](https://user-images.githubusercontent.com/51966857/156086595-c267b157-2d23-4467-83d7-f4da20acebee.png)
![image](https://user-images.githubusercontent.com/51966857/156086626-d4458d76-8c4a-4bf7-9302-eb77ac6b1d18.png)
![image (1)](https://user-images.githubusercontent.com/51966857/156086637-3a7fcb81-f1b1-40c8-9599-ba2152455694.png)
